export type ApiSurfaceMode = "enforced" | "planned"

export interface PackageApiSurfaceManifest {
  packageName: string
  declarationPath: string
  runtimePath: string
  mode: ApiSurfaceMode
  declarationExports: readonly string[]
  runtimeExports: readonly string[]
  note?: string
}

export const apiSurfaceManifest = [
  {
    packageName: "@bc-grid/core",
    declarationPath: "packages/core/dist/index.d.ts",
    runtimePath: "packages/core/dist/index.js",
    mode: "enforced",
    runtimeExports: [
      "emptyBcPivotState",
      "emptyBcRangeSelection",
      "expandRangeTo",
      "forEachSelectedRowId",
      "isAllSelection",
      "isExplicitSelection",
      "isFilteredSelection",
      "newRangeAt",
      "normaliseRange",
      "parseRangeSelection",
      "rangeBounds",
      "rangeClear",
      "rangeContains",
      "rangeKeydown",
      "rangePointerDown",
      "rangePointerMove",
      "rangePointerUp",
      "rangeSelectAll",
      "rangesContain",
      "serializeRangeSelection",
    ],
    declarationExports: [
      "BcAggregation",
      "BcAggregationResultDTO",
      "BcBuiltInColumnFilterType",
      "BcCellPosition",
      "BcColumnFilter",
      "BcColumnFilterType",
      "BcColumnFormat",
      "BcColumnStateEntry",
      "BcGridApi",
      "BcGridColumn",
      "BcGridFilter",
      "BcGridIdentity",
      "BcGridPasteTsvCommit",
      "BcGridPasteTsvFailure",
      "BcGridPasteTsvFailureCode",
      "BcGridPasteTsvOverflowMode",
      "BcGridPasteTsvParams",
      "BcGridPasteTsvParseDiagnostic",
      "BcGridPasteTsvParseDiagnosticCode",
      "BcGridPasteTsvResult",
      "BcGridPasteTsvRowPatch",
      "BcGridPasteTsvSkipReason",
      "BcGridPasteTsvSkippedCell",
      "BcGridPasteTsvSuccess",
      "BcGridSort",
      "BcGridStateProps",
      "BcNormalisedRange",
      "BcPaginationState",
      "BcPivotCellDTO",
      "BcPivotColNodeDTO",
      "BcPivotRowNodeDTO",
      "BcPivotState",
      "BcPivotValue",
      "BcPivotedDataDTO",
      "BcRange",
      "BcRangeKeyAction",
      "BcRangeSelection",
      "BcRowId",
      "BcRowPatch",
      "BcRowPatchFailure",
      "BcRowPatchFailureCode",
      "BcRowPatchResult",
      "BcRowState",
      "BcScrollAlign",
      "BcScrollOptions",
      "BcSelection",
      "BcServerGridApi",
      "BcValidationResult",
      "ColumnId",
      "LoadServerBlock",
      "LoadServerPage",
      "LoadServerTreeChildren",
      "RowId",
      "ServerBlockCacheOptions",
      "ServerBlockKey",
      "ServerBlockQuery",
      "ServerBlockResult",
      "ServerCacheDiagnostics",
      "ServerCacheBlock",
      "ServerColumnFilter",
      "ServerExportQuery",
      "ServerExportResult",
      "ServerFilter",
      "ServerFilterGroup",
      "ServerGroup",
      "ServerGroupKey",
      "ServerInvalidation",
      "ServerLoadContext",
      "ServerLoadDiagnostics",
      "ServerLoadStatus",
      "ServerMutationResult",
      "ServerPagedQuery",
      "ServerPagedResult",
      "ServerQueryDiagnostics",
      "ServerQueryBase",
      "ServerRowIdentity",
      "ServerRowModelDiagnostics",
      "ServerRowModelEvent",
      "ServerRowModelMode",
      "ServerRowModelState",
      "ServerRowPatch",
      "ServerRowUpdate",
      "ServerSelection",
      "ServerSelectionSnapshot",
      "ServerSort",
      "ServerTreeQuery",
      "ServerTreeResult",
      "ServerTreeRow",
      "ServerViewDiagnostics",
      "ServerViewState",
      "SetFilterOption",
      "SetFilterOptionLoadParams",
      "SetFilterOptionLoadResult",
      "SetFilterOptionProvider",
      "emptyBcPivotState",
      "emptyBcRangeSelection",
      "expandRangeTo",
      "forEachSelectedRowId",
      "isAllSelection",
      "isExplicitSelection",
      "isFilteredSelection",
      "newRangeAt",
      "normaliseRange",
      "parseRangeSelection",
      "rangeBounds",
      "rangeClear",
      "rangeContains",
      "rangeKeydown",
      "rangePointerDown",
      "rangePointerMove",
      "rangePointerUp",
      "rangeSelectAll",
      "rangesContain",
      "serializeRangeSelection",
    ],
  },
  {
    packageName: "@bc-grid/react",
    declarationPath: "packages/react/dist/index.d.ts",
    runtimePath: "packages/react/dist/index.js",
    mode: "enforced",
    runtimeExports: [
      "BC_GRID_ROW_DRAG_MIME",
      "BC_SAVED_VIEW_VERSION",
      "BcEditGrid",
      "BcGrid",
      "BcServerGrid",
      "BcStatusBar",
      "DEFAULT_CONTEXT_MENU_ITEMS",
      "applySavedViewLayout",
      "createSavedView",
      "forEachSelectedRowId",
      "isAllSelection",
      "isExplicitSelection",
      "isFilteredSelection",
      "buildClientTree",
      "compactVisibleAncestors",
      "expandVisibleAncestors",
      "flattenClientTree",
      "migrateSavedViewLayout",
      "registerReactFilterDefinition",
      "resolveVisibleSegments",
      "useAggregations",
      "useBcGridApi",
      "useBcGridState",
      "resolveInitialServerGridState",
      "resolveServerGridActiveMode",
      "resolveServerGridMissingLoaderMessage",
      "useServerGrid",
      "useServerInfiniteGrid",
      "useServerPagedGrid",
      "useServerRowUpdates",
      "useServerTreeGrid",
    ],
    declarationExports: [
      "BC_GRID_ROW_DRAG_MIME",
      "BcAggregationFormatterParams",
      "BcAggregationScope",
      "BcBuiltInColumnFilterType",
      "BcBulkActionsContext",
      "BcCellEditCommitEvent",
      "BcClientTreeData",
      "ClientTreeIndex",
      "buildClientTree",
      "compactVisibleAncestors",
      "expandVisibleAncestors",
      "flattenClientTree",
      "BcCellEditor",
      "BcCellEditorPrepareParams",
      "BcCellEditorProps",
      "BcCellPosition",
      "BcCellRendererParams",
      "BcClipboardPayload",
      "BcColumnFilter",
      "BcColumnFilterType",
      "BcColumnFormat",
      "BcColumnStateEntry",
      "BcContextMenuBuiltinItem",
      "BcContextMenuContext",
      "BcContextMenuCustomItem",
      "BcContextMenuItem",
      "BcContextMenuItems",
      "BcContextMenuSubmenuItem",
      "BcContextMenuToggleItem",
      "BcDetailPanelParams",
      "BcEditGrid",
      "BcEditGridAction",
      "BcEditGridInsertRowParams",
      "BcEditGridProps",
      "BcEditGridRowActionParams",
      "BcEditMove",
      "BcFilterDefinition",
      "BcFilterEditorProps",
      "BcFilterPredicateContext",
      "BcFilterUserContext",
      "BcFiscalCalendar",
      "BcGrid",
      "BcGridApi",
      "BcGridColumn",
      "BcGridDensity",
      "BcGridFilter",
      "BcGridLayoutState",
      "BcGridMessages",
      "BcGridPasteTsvCommit",
      "BcGridPasteTsvFailure",
      "BcGridPasteTsvFailureCode",
      "BcGridPasteTsvOverflowMode",
      "BcGridPasteTsvParams",
      "BcGridPasteTsvParseDiagnostic",
      "BcGridPasteTsvParseDiagnosticCode",
      "BcGridPasteTsvResult",
      "BcGridPasteTsvRowPatch",
      "BcGridPasteTsvSkipReason",
      "BcGridPasteTsvSkippedCell",
      "BcGridPasteTsvSuccess",
      "BcGridProps",
      "BcGridRowParams",
      "BcGridSort",
      "BcGridStateBindings",
      "BcGridStateBoundProps",
      "BcGridStateDispatch",
      "BcGridStateProps",
      "BcGridStateValues",
      "BcGridUrlStatePersistence",
      "BcNormalisedRange",
      "BcPaginationState",
      "BcRange",
      "BcRangeBeforeCopyEvent",
      "BcRangeBeforeCopyHook",
      "BcRangeCopyEvent",
      "BcRangeCopyHook",
      "BcRangeKeyAction",
      "BcRangeSelection",
      "BcRangeSelectionOptions",
      "BcReactFilterDefinition",
      "BcReactGridColumn",
      "BcRowDragOverEvent",
      "BcRowDragOverHandler",
      "BcRowDropAction",
      "BcRowDropEvent",
      "BcRowDropHandler",
      "BcRowPatch",
      "BcRowPatchFailure",
      "BcRowPatchFailureCode",
      "BcRowPatchResult",
      "BcSavedView",
      "BcSavedViewInput",
      "BcSavedViewLayoutApplier",
      "BcSavedViewLayoutInput",
      "BcSavedViewScope",
      "BcSelection",
      "BcServerRowUpdateHandler",
      "BcServerRowUpdateSubscribe",
      "BcServerRowUpdateUnsubscribe",
      "BcServerEditMutationEvent",
      "BcServerEditMutationHandler",
      "BcServerEditMutationProps",
      "BcServerEditPatchFactory",
      "BcServerGrid",
      "BcServerGridApi",
      "BcServerGridProps",
      "BcSidebarBuiltInPanel",
      "BcSidebarContext",
      "BcSidebarCustomPanel",
      "BcSidebarPanel",
      "BcStatusBar",
      "EditorTabWraparound",
      "BcStatusBarContext",
      "BcStatusBarCustomSegment",
      "BcStatusBarSegment",
      "BcUserColumnSettings",
      "BcUserSettings",
      "BcUserSettingsStore",
      "BcValidationResult",
      "BC_SAVED_VIEW_VERSION",
      "ColumnId",
      "CreateSavedViewOptions",
      "DEFAULT_CONTEXT_MENU_ITEMS",
      "LoadServerBlock",
      "LoadServerPage",
      "LoadServerTreeChildren",
      "RowId",
      "ServerBlockQuery",
      "ServerBlockResult",
      "ServerCacheDiagnostics",
      "ServerLoadContext",
      "ServerLoadDiagnostics",
      "ServerLoadStatus",
      "ServerMutationResult",
      "ServerPagedQuery",
      "ServerPagedResult",
      "ServerQueryDiagnostics",
      "ServerRowModelDiagnostics",
      "ServerRowPatch",
      "ServerRowUpdate",
      "ServerTreeQuery",
      "ServerTreeResult",
      "ServerTreeRow",
      "ServerViewDiagnostics",
      "SetFilterOption",
      "SetFilterOptionLoadParams",
      "SetFilterOptionLoadResult",
      "SetFilterOptionProvider",
      "applySavedViewLayout",
      "createSavedView",
      "migrateSavedViewLayout",
      "registerReactFilterDefinition",
      "UseAggregationsOptions",
      "UseBcGridStateOptions",
      "UseServerGridActions",
      "UseServerGridBoundProps",
      "UseServerGridInitial",
      "UseServerGridOptions",
      "UseServerGridResult",
      "UseServerGridState",
      "UseServerInfiniteGridActions",
      "UseServerInfiniteGridBoundProps",
      "UseServerInfiniteGridInitial",
      "UseServerInfiniteGridOptions",
      "UseServerInfiniteGridResult",
      "UseServerInfiniteGridState",
      "UseServerPagedGridActions",
      "UseServerPagedGridBoundProps",
      "UseServerPagedGridInitial",
      "UseServerPagedGridOptions",
      "UseServerPagedGridResult",
      "UseServerPagedGridState",
      "UseServerTreeGridActions",
      "UseServerTreeGridBoundProps",
      "UseServerTreeGridInitial",
      "UseServerTreeGridOptions",
      "UseServerTreeGridResult",
      "UseServerTreeGridState",
      "forEachSelectedRowId",
      "isAllSelection",
      "isExplicitSelection",
      "isFilteredSelection",
      "resolveVisibleSegments",
      "useAggregations",
      "useBcGridApi",
      "useBcGridState",
      "resolveInitialServerGridState",
      "resolveServerGridActiveMode",
      "resolveServerGridMissingLoaderMessage",
      "useServerGrid",
      "useServerInfiniteGrid",
      "useServerPagedGrid",
      "useServerRowUpdates",
      "useServerTreeGrid",
    ],
  },
  {
    packageName: "@bc-grid/virtualizer",
    declarationPath: "packages/virtualizer/dist/index.d.ts",
    runtimePath: "packages/virtualizer/dist/index.js",
    mode: "enforced",
    runtimeExports: ["DOMRenderer", "Virtualizer"],
    declarationExports: [
      "DOMRenderer",
      "DOMRendererOptions",
      "InFlightHandle",
      "RenderCellParams",
      "ScrollAlign",
      "VirtualCol",
      "VirtualColumnA11yMeta",
      "VirtualItem",
      "VirtualOptions",
      "VirtualRow",
      "VirtualRowA11yMeta",
      "VirtualWindow",
      "Virtualizer",
      "VirtualizerA11yInput",
      "VirtualizerOptions",
    ],
    note: "Includes React-internal DOMRenderer exports documented in packages/virtualizer/src/index.ts.",
  },
  {
    packageName: "@bc-grid/animations",
    declarationPath: "packages/animations/dist/index.d.ts",
    runtimePath: "packages/animations/dist/index.js",
    mode: "enforced",
    runtimeExports: [
      "AnimationBudget",
      "DEFAULT_ANIMATION_MAX_IN_FLIGHT",
      "HARD_ANIMATION_MAX_IN_FLIGHT",
      "calculateFlipDelta",
      "createFlashKeyframes",
      "createFlipKeyframes",
      "createSlideKeyframes",
      "flash",
      "flip",
      "playFlip",
      "prefersReducedMotion",
      "readFlipRect",
      "resolveMotionPolicy",
      "shouldAnimateDelta",
      "slide",
    ],
    declarationExports: [
      "AnimationBudget",
      "AnimationBudgetOptions",
      "AnimationOptions",
      "DEFAULT_ANIMATION_MAX_IN_FLIGHT",
      "FlipDelta",
      "FlipOptions",
      "FlipRect",
      "FlipTarget",
      "HARD_ANIMATION_MAX_IN_FLIGHT",
      "MotionPolicy",
      "SlideDirection",
      "SlideOptions",
      "calculateFlipDelta",
      "createFlashKeyframes",
      "createFlipKeyframes",
      "createSlideKeyframes",
      "flash",
      "flip",
      "playFlip",
      "prefersReducedMotion",
      "readFlipRect",
      "resolveMotionPolicy",
      "shouldAnimateDelta",
      "slide",
    ],
    note: "Matches the shipped animations implementation report; docs/api.md lists the smaller consumer-facing subset.",
  },
  {
    packageName: "@bc-grid/theming",
    declarationPath: "packages/theming/dist/index.d.ts",
    runtimePath: "packages/theming/dist/index.js",
    mode: "enforced",
    runtimeExports: [
      "bcGridDensities",
      "bcGridDensityClasses",
      "bcGridPreset",
      "bcGridThemeVars",
      "createBcGridThemeVars",
      "getBcGridDensityClass",
      "getBcGridDensityVars",
    ],
    declarationExports: [
      "BcGridCssVar",
      "BcGridCssVars",
      "BcGridDensity",
      "bcGridDensities",
      "bcGridDensityClasses",
      "bcGridPreset",
      "bcGridThemeVars",
      "createBcGridThemeVars",
      "getBcGridDensityClass",
      "getBcGridDensityVars",
    ],
  },
  {
    packageName: "@bc-grid/aggregations",
    declarationPath: "packages/aggregations/dist/index.d.ts",
    runtimePath: "packages/aggregations/dist/index.js",
    mode: "enforced",
    runtimeExports: [
      "aggregate",
      "aggregateColumns",
      "aggregateGroups",
      "aggregationRegistry",
      "avg",
      "count",
      "max",
      "min",
      "pivot",
      "registerAggregation",
      "sum",
    ],
    declarationExports: [
      "AggregateOptions",
      "Aggregation",
      "AggregationContext",
      "AggregationResult",
      "BcPivotCell",
      "BcPivotColNode",
      "BcPivotRowNode",
      "BcPivotedData",
      "PivotOptions",
      "aggregate",
      "aggregateColumns",
      "aggregateGroups",
      "aggregationRegistry",
      "avg",
      "count",
      "max",
      "min",
      "pivot",
      "registerAggregation",
      "sum",
    ],
  },
  {
    packageName: "@bc-grid/filters",
    declarationPath: "packages/filters/dist/index.d.ts",
    runtimePath: "packages/filters/dist/index.js",
    mode: "enforced",
    runtimeExports: [
      "BcDefaultFilterRegistry",
      "booleanFilter",
      "builtinFilterDefinitions",
      "columnFilterFromSerializedCriteria",
      "createFilterRegistry",
      "dateFilter",
      "dateRangeFilter",
      "filterRegistry",
      "getFilterDefinition",
      "isBlankSetFilterValue",
      "matchesColumnFilter",
      "matchesFilter",
      "numberFilter",
      "numberRangeFilter",
      "registerFilter",
      "serializeColumnFilterCriteria",
      "setFilter",
      "setFilterValueKey",
      "setFilterValueKeys",
      "textFilter",
    ],
    declarationExports: [
      "BcDefaultFilterRegistry",
      "BcFilterCellValue",
      "BcFilterDefinition",
      "BcFilterOperatorDefinition",
      "BcFilterOperatorValueShape",
      "BcFilterPredicateContext",
      "BcFilterPredicateValue",
      "BcFilterRegistry",
      "BcFilterUserContext",
      "MatchesFilterOptions",
      "BcFiscalCalendar",
      "booleanFilter",
      "builtinFilterDefinitions",
      "columnFilterFromSerializedCriteria",
      "createFilterRegistry",
      "dateFilter",
      "dateRangeFilter",
      "filterRegistry",
      "getFilterDefinition",
      "isBlankSetFilterValue",
      "matchesColumnFilter",
      "matchesFilter",
      "numberFilter",
      "numberRangeFilter",
      "registerFilter",
      "serializeColumnFilterCriteria",
      "setFilter",
      "setFilterValueKey",
      "setFilterValueKeys",
      "textFilter",
    ],
  },
  {
    packageName: "@bc-grid/export",
    declarationPath: "packages/export/dist/index.d.ts",
    runtimePath: "packages/export/dist/index.js",
    mode: "enforced",
    runtimeExports: ["exportServerRows", "toCsv", "toExcel", "toPdf"],
    declarationExports: [
      "ExportOptions",
      "ExportResult",
      "LoadAllServerExportRows",
      "ServerExportContext",
      "ServerExportFlowOptions",
      "ServerExportHandler",
      "ServerExportRowsResult",
      "exportServerRows",
      "toCsv",
      "toExcel",
      "toPdf",
    ],
    note: "Serializers plus server-mode export coordinator. XLSX uses ExcelJS peer-dep, PDF uses jsPDF peer-dep.",
  },
  {
    packageName: "@bc-grid/server-row-model",
    declarationPath: "packages/server-row-model/dist/index.d.ts",
    runtimePath: "packages/server-row-model/dist/index.js",
    mode: "planned",
    runtimeExports: [
      "ServerBlockCache",
      "createServerRowModel",
      "defaultBlockKey",
      "summarizeServerCache",
      "summarizeServerQuery",
      "summarizeServerRowModelState",
      "summarizeServerViewState",
    ],
    declarationExports: [
      "ServerBlockCache",
      "createServerRowModel",
      "defaultBlockKey",
      "summarizeServerCache",
      "summarizeServerQuery",
      "summarizeServerRowModelState",
      "summarizeServerViewState",
    ],
  },
  {
    packageName: "@bc-grid/editors",
    declarationPath: "packages/editors/dist/index.d.ts",
    runtimePath: "packages/editors/dist/index.js",
    mode: "enforced",
    runtimeExports: [
      "autocompleteEditor",
      "checkboxEditor",
      "dateEditor",
      "datetimeEditor",
      "multiSelectEditor",
      "numberEditor",
      "parseLocaleNumber",
      "selectEditor",
      "textEditor",
      "timeEditor",
    ],
    declarationExports: [
      "autocompleteEditor",
      "checkboxEditor",
      "dateEditor",
      "datetimeEditor",
      "multiSelectEditor",
      "numberEditor",
      "parseLocaleNumber",
      "selectEditor",
      "textEditor",
      "timeEditor",
    ],
    note: "v0.1: ships editor-text + editor-number + editor-date + editor-time + editor-datetime + editor-select + editor-multi-select + editor-autocomplete; v0.4 adds editor-checkbox.",
  },
  {
    packageName: "@bc-grid/enterprise",
    declarationPath: "packages/enterprise/dist/index.d.ts",
    runtimePath: "packages/enterprise/dist/index.js",
    mode: "enforced",
    runtimeExports: [],
    declarationExports: [],
    note: "Reserved Q5 package; v0.1 ships no exports.",
  },
] satisfies readonly PackageApiSurfaceManifest[]
