export type ApiSurfaceMode = "enforced" | "planned"

export interface PackageApiSurfaceManifest {
  packageName: string
  declarationPath: string
  runtimePath: string
  mode: ApiSurfaceMode
  declarationExports: readonly string[]
  runtimeExports: readonly string[]
  note?: string
}

export const apiSurfaceManifest = [
  {
    packageName: "@bc-grid/core",
    declarationPath: "packages/core/dist/index.d.ts",
    runtimePath: "packages/core/dist/index.js",
    mode: "enforced",
    runtimeExports: [],
    declarationExports: [
      "BcAggregation",
      "BcCellPosition",
      "BcColumnFilter",
      "BcColumnFormat",
      "BcColumnStateEntry",
      "BcGridApi",
      "BcGridColumn",
      "BcGridFilter",
      "BcGridIdentity",
      "BcGridSort",
      "BcGridStateProps",
      "BcPaginationState",
      "BcRange",
      "BcRowId",
      "BcRowState",
      "BcScrollAlign",
      "BcScrollOptions",
      "BcSelection",
      "BcServerGridApi",
      "BcValidationResult",
      "ColumnId",
      "LoadServerBlock",
      "LoadServerPage",
      "LoadServerTreeChildren",
      "RowId",
      "ServerBlockCacheOptions",
      "ServerBlockKey",
      "ServerBlockQuery",
      "ServerBlockResult",
      "ServerCacheBlock",
      "ServerColumnFilter",
      "ServerExportQuery",
      "ServerExportResult",
      "ServerFilter",
      "ServerFilterGroup",
      "ServerGroup",
      "ServerGroupKey",
      "ServerInvalidation",
      "ServerLoadContext",
      "ServerMutationResult",
      "ServerPagedQuery",
      "ServerPagedResult",
      "ServerQueryBase",
      "ServerRowIdentity",
      "ServerRowModelEvent",
      "ServerRowModelMode",
      "ServerRowModelState",
      "ServerRowPatch",
      "ServerRowUpdate",
      "ServerSelection",
      "ServerSelectionSnapshot",
      "ServerSort",
      "ServerTreeQuery",
      "ServerTreeResult",
      "ServerTreeRow",
      "ServerViewState",
    ],
  },
  {
    packageName: "@bc-grid/react",
    declarationPath: "packages/react/dist/index.d.ts",
    runtimePath: "packages/react/dist/index.js",
    mode: "enforced",
    runtimeExports: ["BcEditGrid", "BcGrid", "BcServerGrid", "useBcGridApi"],
    declarationExports: [
      "BcCellEditCommitEvent",
      "BcCellEditor",
      "BcCellEditorPrepareParams",
      "BcCellEditorProps",
      "BcCellPosition",
      "BcCellRendererParams",
      "BcColumnFilter",
      "BcColumnFormat",
      "BcColumnStateEntry",
      "BcEditGrid",
      "BcEditGridAction",
      "BcEditGridProps",
      "BcFilterDefinition",
      "BcFilterEditorProps",
      "BcGrid",
      "BcGridApi",
      "BcGridColumn",
      "BcGridDensity",
      "BcGridFilter",
      "BcGridMessages",
      "BcGridProps",
      "BcGridSort",
      "BcGridStateProps",
      "BcPaginationState",
      "BcReactFilterDefinition",
      "BcReactGridColumn",
      "BcSelection",
      "BcServerGrid",
      "BcServerGridApi",
      "BcServerGridProps",
      "BcValidationResult",
      "ColumnId",
      "LoadServerBlock",
      "LoadServerPage",
      "LoadServerTreeChildren",
      "RowId",
      "ServerBlockQuery",
      "ServerBlockResult",
      "ServerLoadContext",
      "ServerPagedQuery",
      "ServerPagedResult",
      "ServerTreeQuery",
      "ServerTreeResult",
      "useBcGridApi",
    ],
  },
  {
    packageName: "@bc-grid/virtualizer",
    declarationPath: "packages/virtualizer/dist/index.d.ts",
    runtimePath: "packages/virtualizer/dist/index.js",
    mode: "enforced",
    runtimeExports: ["DOMRenderer", "Virtualizer"],
    declarationExports: [
      "DOMRenderer",
      "DOMRendererOptions",
      "InFlightHandle",
      "RenderCellParams",
      "ScrollAlign",
      "VirtualCol",
      "VirtualColumnA11yMeta",
      "VirtualItem",
      "VirtualOptions",
      "VirtualRow",
      "VirtualRowA11yMeta",
      "VirtualWindow",
      "Virtualizer",
      "VirtualizerA11yInput",
      "VirtualizerOptions",
    ],
    note: "Includes React-internal DOMRenderer exports documented in packages/virtualizer/src/index.ts.",
  },
  {
    packageName: "@bc-grid/animations",
    declarationPath: "packages/animations/dist/index.d.ts",
    runtimePath: "packages/animations/dist/index.js",
    mode: "enforced",
    runtimeExports: [
      "AnimationBudget",
      "DEFAULT_ANIMATION_MAX_IN_FLIGHT",
      "HARD_ANIMATION_MAX_IN_FLIGHT",
      "calculateFlipDelta",
      "createFlashKeyframes",
      "createFlipKeyframes",
      "createSlideKeyframes",
      "flash",
      "flip",
      "playFlip",
      "prefersReducedMotion",
      "readFlipRect",
      "resolveMotionPolicy",
      "shouldAnimateDelta",
      "slide",
    ],
    declarationExports: [
      "AnimationBudget",
      "AnimationBudgetOptions",
      "AnimationOptions",
      "DEFAULT_ANIMATION_MAX_IN_FLIGHT",
      "FlipDelta",
      "FlipOptions",
      "FlipRect",
      "FlipTarget",
      "HARD_ANIMATION_MAX_IN_FLIGHT",
      "MotionPolicy",
      "SlideDirection",
      "SlideOptions",
      "calculateFlipDelta",
      "createFlashKeyframes",
      "createFlipKeyframes",
      "createSlideKeyframes",
      "flash",
      "flip",
      "playFlip",
      "prefersReducedMotion",
      "readFlipRect",
      "resolveMotionPolicy",
      "shouldAnimateDelta",
      "slide",
    ],
    note: "Matches the shipped animations implementation report; docs/api.md lists the smaller consumer-facing subset.",
  },
  {
    packageName: "@bc-grid/theming",
    declarationPath: "packages/theming/dist/index.d.ts",
    runtimePath: "packages/theming/dist/index.js",
    mode: "enforced",
    runtimeExports: [
      "bcGridDensities",
      "bcGridDensityClasses",
      "bcGridPreset",
      "bcGridThemeVars",
      "createBcGridThemeVars",
      "getBcGridDensityClass",
      "getBcGridDensityVars",
    ],
    declarationExports: [
      "BcGridCssVar",
      "BcGridCssVars",
      "BcGridDensity",
      "bcGridDensities",
      "bcGridDensityClasses",
      "bcGridPreset",
      "bcGridThemeVars",
      "createBcGridThemeVars",
      "getBcGridDensityClass",
      "getBcGridDensityVars",
    ],
  },
  {
    packageName: "@bc-grid/aggregations",
    declarationPath: "packages/aggregations/dist/index.d.ts",
    runtimePath: "packages/aggregations/dist/index.js",
    mode: "planned",
    runtimeExports: ["avg", "count", "max", "min", "registerAggregation", "sum"],
    declarationExports: [
      "Aggregation",
      "AggregationContext",
      "AggregationResult",
      "avg",
      "count",
      "max",
      "min",
      "registerAggregation",
      "sum",
    ],
  },
  {
    packageName: "@bc-grid/filters",
    declarationPath: "packages/filters/dist/index.d.ts",
    runtimePath: "packages/filters/dist/index.js",
    mode: "planned",
    runtimeExports: [
      "booleanFilter",
      "dateFilter",
      "matchesFilter",
      "numberFilter",
      "registerFilter",
      "setFilter",
      "textFilter",
    ],
    declarationExports: [
      "BcFilterDefinition",
      "booleanFilter",
      "dateFilter",
      "matchesFilter",
      "numberFilter",
      "registerFilter",
      "setFilter",
      "textFilter",
    ],
  },
  {
    packageName: "@bc-grid/export",
    declarationPath: "packages/export/dist/index.d.ts",
    runtimePath: "packages/export/dist/index.js",
    mode: "enforced",
    runtimeExports: ["toCsv", "toExcel", "toPdf"],
    declarationExports: ["ExportOptions", "ExportResult", "toCsv", "toExcel", "toPdf"],
    note: "CSV is implemented for Q1; XLSX and PDF exports are reserved stubs until their follow-up tasks.",
  },
  {
    packageName: "@bc-grid/server-row-model",
    declarationPath: "packages/server-row-model/dist/index.d.ts",
    runtimePath: "packages/server-row-model/dist/index.js",
    mode: "planned",
    runtimeExports: ["ServerBlockCache", "createServerRowModel", "defaultBlockKey"],
    declarationExports: ["ServerBlockCache", "createServerRowModel", "defaultBlockKey"],
  },
  {
    packageName: "@bc-grid/editors",
    declarationPath: "packages/editors/dist/index.d.ts",
    runtimePath: "packages/editors/dist/index.js",
    mode: "enforced",
    runtimeExports: [],
    declarationExports: [],
    note: "Reserved Q2 package; v0.1 ships no exports.",
  },
  {
    packageName: "@bc-grid/enterprise",
    declarationPath: "packages/enterprise/dist/index.d.ts",
    runtimePath: "packages/enterprise/dist/index.js",
    mode: "enforced",
    runtimeExports: [],
    declarationExports: [],
    note: "Reserved Q5 package; v0.1 ships no exports.",
  },
] satisfies readonly PackageApiSurfaceManifest[]
